SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

CREATE DATABASE `dir` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `dir`;

CREATE TABLE IF NOT EXISTS `contact` (
  `ext` varchar(8) NOT NULL DEFAULT '',
  `name` varchar(125) NOT NULL DEFAULT '',
  `dept` varchar(125) NOT NULL DEFAULT '',
  PRIMARY KEY (`ext`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

